name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "README.md"
      - "LICENSE"
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "README.md"
      - "LICENSE"
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        preset: [static_release]
        c_compiler: [gcc, clang, cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
            generator: Visual Studio 17 2022
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
            generator: Ninja
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
            generator: Ninja
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: >
        cmake --preset ${{ matrix.preset }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -G "${{ matrix.generator }}"
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build --preset ${{ matrix.preset }}
